name: model-eval-app
metadata:
  template: model-eval-app@0.0.1

services:
  web:
    language: js
    host: containerapp
    project: .
    docker:
      path: ./Dockerfile
      context: .

pipeline:
  secrets:
    - POSTGRES_ADMIN_LOGIN
    - POSTGRES_ADMIN_PASSWORD
